fName = 'C:\\Users\\Pankil\\Documents\\MATLAB\\Research\\Code V2\\Objects\\SiPin.mat';
LAMBDAMIN = 400; LAMBDAPEAK = 900; LAMBDAMAX = 1100;
QEFFMIN = 65; QEFFPEAK = 90; QEFCUTOFFF = 0;



LAMBDAS = LAMBDAMIN:1:LAMBDAMAX;
RESPONSIVITY = QEFFL*LAMBDAS*1e3/1.24;